from collections.abc import Awaitable, Callable, Iterator, Sequence
from types import TracebackType
from typing import Any, overload

import httpx2

_RouteResult = httpx2.Request | httpx2.Response | None
_SideEffect = (
    Callable[..., _RouteResult | Awaitable[_RouteResult]]
    | Exception
    | type[Exception]
    | Iterator[httpx2.Response | Exception | type[Exception]]
    | Sequence[httpx2.Response | Exception | type[Exception]]
)


class Call:
    request: httpx2.Request
    optional_response: httpx2.Response | None
    @property
    def response(self) -> httpx2.Response: ...
    @property
    def has_response(self) -> bool: ...


class CallList(list[Call]):
    @property
    def called(self) -> bool: ...
    @property
    def call_count(self) -> int: ...
    @property
    def last(self) -> Call: ...


class Route:
    calls: CallList
    def mock(
        self,
        return_value: httpx2.Response | None = None,
        *,
        side_effect: _SideEffect | None = None,
    ) -> Route: ...
    def respond(self, status_code: int = 200, **kwargs: Any) -> Route: ...
    def pass_through(self, value: bool = True) -> Route: ...
    @property
    def called(self) -> bool: ...
    @property
    def call_count(self) -> int: ...


class Router:
    routes: Any
    calls: CallList
    def request(
        self, method: str, url: Any = None, *, name: str | None = None, **lookups: Any
    ) -> Route: ...
    def get(self, url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
    def post(self, url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
    def put(self, url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
    def patch(self, url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
    def delete(self, url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
    def head(self, url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
    def options(self, url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...


class MockRouter(Router):
    @overload
    def __call__(
        self,
        func: None = None,
        *,
        assert_all_called: bool | None = None,
        assert_all_mocked: bool | None = None,
        base_url: str | None = None,
        using: str | None = ...,
    ) -> MockRouter: ...
    @overload
    def __call__(
        self,
        func: Callable[..., Any],
        *,
        assert_all_called: bool | None = None,
        assert_all_mocked: bool | None = None,
        base_url: str | None = None,
        using: str | None = ...,
    ) -> Callable[..., Any]: ...
    def __enter__(self) -> MockRouter: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_value: BaseException | None = None,
        traceback: TracebackType | None = None,
    ) -> None: ...
    async def __aenter__(self) -> MockRouter: ...
    async def __aexit__(self, *args: Any) -> None: ...


mock: MockRouter
routes: Any
calls: CallList

def start() -> None: ...
def stop(*, clear: bool = True, reset: bool = True) -> None: ...
def clear() -> None: ...
def reset() -> None: ...
def pop(name: str, default: Any = ...) -> Route | Any: ...
def route(*patterns: Any, name: str | None = None, **lookups: Any) -> Route: ...
def add(route: Route, *, name: str | None = None) -> Route: ...
def request(method: str, url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
def get(url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
def post(url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
def put(url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
def patch(url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
def delete(url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
def head(url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
def options(url: Any = None, *, name: str | None = None, **lookups: Any) -> Route: ...
