[build-system]
requires = ["hatchling>=1.27.0,<2"]
build-backend = "hatchling.build"

[project]
name = "vercel-blob"
dynamic = ["version", "dependencies"]
description = "Python SDK for Vercel Blob"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE", "LICENSE.*"]

[tool.hatch.metadata.hooks.custom]
path = "hatch_build.py"

[tool.vercel.release.dependencies]
dependencies = []

[tool.hatch.version]
path = "vercel/blob/version.py"

[tool.hatch.build.targets.sdist]
force-include = { "../../scripts/hatch_build.py" = "/_vercel_hatch_build.py" }
include = [
    "/vercel/blob/**/*.py",
    "/vercel/blob/py.typed",
    "/README.md",
    "/pyproject.toml",
    "/hatch_build.py",
    "/LICENSE",
]
exclude = ["/**/__pycache__"]

[tool.hatch.build.targets.wheel]
dev-mode-dirs = ["."]
only-include = ["/vercel/blob"]
exclude = ["/**/__pycache__"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "--no-header --capture=tee-sys"

[tool.poe]
include = "../../scripts/poe/poe.toml"
verbosity = -1

[tool.mypy]
cache_dir = "../../.mypy_cache/vercel-blob"
explicit_package_bases = true
packages = ["vercel.blob"]

[tool.poe.tasks.typecheck]
cmd = "$MYPY"
