"""Transitional aliases for HTTP infrastructure now owned by internal core."""

from vercel.internal.core.http import (
    DEFAULT_API_BASE_URL,
    DEFAULT_TIMEOUT,
    AsyncTransport,
    BaseTransport,
    BytesBody,
    JSONBody,
    RawBody,
    ReadResponsePolicy,
    RequestBody,
    RetryPolicy,
    SleepFn,
    StreamingRequest,
    StreamingResponse,
    SyncTransport,
    TransportOptions,
    create_base_async_client,
    create_base_client,
    extract_structured_error,
)

__all__ = [
    "DEFAULT_API_BASE_URL",
    "DEFAULT_TIMEOUT",
    "BaseTransport",
    "SyncTransport",
    "AsyncTransport",
    "TransportOptions",
    "JSONBody",
    "BytesBody",
    "RawBody",
    "ReadResponsePolicy",
    "RequestBody",
    "StreamingRequest",
    "StreamingResponse",
    "RetryPolicy",
    "SleepFn",
    "create_base_client",
    "create_base_async_client",
    "extract_structured_error",
]
