name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  lint-test-and-build:
    name: test (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    environment: ci
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    env:
      BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3.2.4

      - name: Sync dependencies
        run: uv sync --python ${{ matrix.python-version }}

      - name: Run tests, including lint and typecheck
        run: ./scripts/test.sh

      - name: Run example tests
        run: ./scripts/test-examples.sh

      - name: Build package
        run: ./scripts/build.sh
